[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[template.environment]
  STATUSKIT_PAGE_TITLE = "Status | Project Naomi"
  STATUSKIT_COMPANY_LOGO = "https://projectnaomi.com/naomi-logo.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "support@projectnaomi.com"
  STATUSKIT_RESOURCES_LINK = "https://projectnaomi.com/dev/docs/"
