[build]
  command = "npm run build"
  publish = "Naomi-Website"

[build.environment]
  CI = "true"

[context.status]
  command = "npm run generate"
  publish = "dist"

[context.npeeditor]
  command = ""
  publish = ""