[build]
  command = "npm run build"
  publish = "Naomi-Website"

[build.environment]
  CI = "true"

[context.status]
  command = "echo 'status'"
  base = "status"

[context.npeeditor]
  command = "echo 'npeeditor'"
  base = "npeeditor"